import type { Metadata } from "next";

import "@/styles/config.scss";
import "@/styles/global.css";
import '@rainbow-me/rainbowkit/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
